# default parameters for lane_filter/lane_filter_node

debug : True
<<<<<<< HEAD
predict_frequency: 50 #40.0 #30.0 # in Hz
=======
predict_frequency: 30.0 # in Hz
>>>>>>> upstream/daffy
lane_filter_histogram_configuration:
  # ADD PARAMETERS HERE
  mean_d_0: 0
  mean_phi_0: 0
  sigma_d_0: 0.1
  sigma_phi_0: 0.1
  delta_d: 0.02
  delta_phi: 0.1
  d_max: 0.3
  d_min: -0.15
<<<<<<< HEAD
  phi_min: -1.2
  phi_max: 1.2
=======
  phi_min: -1.5
  phi_max: 1.5
>>>>>>> upstream/daffy
  linewidth_white: 0.05
  linewidth_yellow: 0.025
  lanewidth: 0.23
  sigma_d_mask: 1.0
  sigma_phi_mask: 2.0
<<<<<<< HEAD
  encoder_resolution: 155
=======
  encoder_resolution: 135
>>>>>>> upstream/daffy
  wheel_radius: 0.0318
  wheel_baseline: 0.1
